<?php

namespace app\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "pages".
 *
 * @property int $id
 * @property string $title
 * @property string $content
 */
class Pages extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'pages';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'content'], 'required'],
            [['content'], 'string'],
            [['title','thumb_img'], 'string', 'max' => 150],
            [['image'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'content' => 'Content',
            'image' => 'Image',
            'thumb_img'=>'Thumb'
        ];
    }

//    public function beforeSave($insert)
//    {
//        $file = UploadedFile::getInstance($this,'image');
//        $filename = $file->name;
//        $file->saveAs(Yii::$app->getBasePath().'/web/uploads/'.$filename);
//        $this->image = $filename;
//        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
//    }
}
